### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by amrdavila** [Lizhen0909/LSHVec#1]
Hi, I installed your LSHVec from source then tried your hashSeq.py script:

python3 /LSHVec-master/scripts/fastseq/hashSeq.py -i all.fasta --hash lsh -o all.fasta.hash -k 15
2019-12-06 09:58:45,755 - hashSeq - INFO - start converting...
2019-12-06 09:58:45,755 - hashSeq - INFO - parameters: {'f': <function convert.<locals>.f at 0x7f2951c8cea0>, 'lsh_file': '', 'create_lsh_only': False, 'batch_size': 100000, 'hash_size': 22, 'out_file': 'all.fasta.hash', 'in_file': 'all.fasta', 'n_thread': 39, 'kmer_size': 15, 'hash_fun': 'lsh', 'bucket': 20000000}
2019-12-06 09:58:45,755 - hashSeq - INFO - creating hash ...
Traceback (most recent call last):
  File "/LSHVec-master/scripts/fastseq/hashSeq.py", line 157, in <module>
    main(sys.argv[1:])
  File "/LSHVec-master/scripts/fastseq/hashSeq.py", line 153, in main
    convert(in_file, out_file, hash_fun, kmer_size, n_thread=n_thread, hash_size=hash_size, batch_size=batch_size, bucket=bucket, create_lsh_only=create_lsh_only, lsh_file=lsh_file)
  File "/LSHVec-master/scripts/fastseq/hashSeq.py", line 66, in convert
    rp.create_hash(lines)
  File "/LSHVec-master/scripts/fastseq/rand_proj.py", line 52, in create_hash
    kmers = self._sample_kmers(lines)
  File "/LSHVec-master/scripts/fastseq/rand_proj.py", line 85, in _sample_kmers
    read = lines[int(np.random.random()*n_reads)].split("\t")[2].strip()
IndexError: list index out of range

I am using Python 3.6.8 in Linux Mint 18

**Comment by Lizhen0909** [comment]
This is because text format issue. fasta file should be converted to tabular format.
By the way, I have updated Tutorial_Toy_Example.ipynb to include  that how a model is used.

**Comment by amrdavila** [comment]
Using the Seq (tabular) format as input solved the problem. Thanks !
